domain_names:
  - domain_name: brave-new-media.com
    asset_server: static.brave-new-media.com
    locations:
      - title: Brave New Media
        subdomain: www

  - domain_name: nightlifechronicle.com
    asset_server: performing-arts-events.com
    locations:
      - title: The Miami Nightlife Chronicle
        subdomain: miami
      - title: The Los Angeles Nightlife Chronicle
        subdomain: los-angeles
  - domain_name: nightlifeherald.com
    asset_server: performing-arts-events.com
    locations:
      - title: The New York Nightlife Herald
        subdomain: new-york

  - domain_name: nightlifeglobe.com
    asset_server: night-club-events.com
    locations:
      - title: The Los Angeles Nightlife Globe
        subdomain: los-angeles
      - title: The New York Nightlife Globe
        subdomain: new-york
      - title: The Las Vegas Nightlife Globe
        subdomain: las-vegas
  - domain_name: nightlifeobserver.com
    asset_server: night-club-events.com
    locations:
      - title: The Boston Nightlife Observer
        subdomain: boston
      - title: The Orange County Nightlife Observer
        subdomain: oc
      - title: The Miami Nightlife Observer
        subdomain: miami