domain_names:
  - domain_name: brave-new-media.com
    asset_server: static.brave-new-media.com
    locations:
      - title: Brave New Media
        subdomain: www

  - domain_name: nightlifechronicle.com
    asset_server: performing-arts-events.com
    locations:
      - title: The Miami Nightlife Chronicle
        subdomain: miami
        application_domain: www
      - title: The Los Angeles Nightlife Chronicle
        subdomain: los-angeles
        application_domain: www
  - domain_name: nightlifeherald.com
    asset_server: performing-arts-events.com
    locations:
      - title: The New York Nightlife Herald
        subdomain: new-york
        application_domain: www

  - domain_name: nightlifeglobe.com
    asset_server: night-club-events.com
    locations:
      - title: The Los Angeles Nightlife Globe
        subdomain: los-angeles
        application_domain: www
      - title: The New York Nightlife Globe
        subdomain: new-york
        application_domain: www
      - title: The Las Vegas Nightlife Globe
        subdomain: las-vegas
        application_domain: www
  - domain_name: nightlifeobserver.com
    asset_server: night-club-events.com
    locations:
      - title: The Boston Nightlife Observer
        subdomain: boston
        application_domain: www
      - title: The Orange County Nightlife Observer
        subdomain: orange-county
        application_domain: www
      - title: The Miami Nightlife Observer
        subdomain: miami
        application_domain: www